name: build and release

on:
  push:
    tags: 
    - 'release/*'
    - 'release/v*'
    - 'v*'

jobs:
  New_Version_Build_And_Release:
    runs-on: windows-latest
    steps:
    # 拉取仓库
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: snow-actions/git-config-user@v1.0.0
      with:
        name: mengyou1024
        email: 1523038073@qq.com
    # 创建changelog
    - name: Create changelog text
      id: changelog
      uses: mengyou1024/action-changelog@v0.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: other,doc,chore
    # 安装依赖
    - name: Install dependencies
      run: |
        choco install 7zip git InnoSetup ninja pedeps -y > nul
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y > nul
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    # 打包输出文件
    - name: Build Release
      run: |
        cmake --preset x64-release
        cmake --build build/x64-release --target PackInstaller Archive
    # 创建Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changes }}
        draft: false
        prerelease: false
    # 上传exe安装程序
    - name: Upload Release Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Roc-MasterInstaller-${{steps.changelog.outputs.version}}.exe
        asset_name: Roc-MasterInstaller-${{steps.changelog.outputs.version}}.exe
        asset_content_type: application/octet-stream
    # 上传归档源码
    - name: Upload Release Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Roc-Master-${{steps.changelog.outputs.version}}-archive.zip
        asset_name: Roc-Master-${{steps.changelog.outputs.version}}-archive.zip
        asset_content_type: application/zip
    # 提交changelog
    - name: Create Changes File
      run: |
        git checkout master
        if((Test-Path "CHANGELOG.md") -ne "True") { echo "" > CHANGELOG.md }
        $CHANGELOG_FILE = Get-Content -Encoding utf8 -Raw -Path CHANGELOG.md
        Clear-Content -Path CHANGELOG.md
        echo "${{steps.changelog.outputs.changelog}}" > CHANGELOG.md
        Add-Content -Path CHANGELOG.md -Value "$CHANGELOG_FILE" -NoNewline
        git add CHANGELOG.md
        git commit -m "Update changelog for version ${{steps.changelog.outputs.version}}"
        git pull
        git push origin master
